---
title: "Working Classes"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# WC 1
## Read data
```{r}
rm(list = ls())
Data = read.table("telecom.txt", header = TRUE, sep = ",")
Data
```

## Read a specific column
```{r}
Data$TotalCharges
```

## Non Available values
```{r}
Data$TotalCharges
is.na(Data$TotalCharges)
which(is.na(Data$TotalCharges))
sum(is.na(Data$TotalCharges))
```

### Changing different NA values
```{r}
Data = read.table("telecom.txt", header = TRUE, sep = ",", na.strings = c("na", "N/A", "NaN","NA"))
Data
sum(is.na(Data$TotalCharges))
```

### Method 1 of handling NA values
We will try to understand the method using generated data.
```{r}
rm(list = ls())
set.seed(100)
Data = rnorm(1000, mean = 100, sd = 25)
head(Data)
summary(Data)
Data.missing = Data
Data.missing[sample(1000,200)]=NA
mean(Data.missing)
```

We remove the NA's from the dataset
```{r}
Data.remove = Data.missing[- which(is.na(Data.missing))]
mean(Data.remove)
sd(Data.remove)
```

```{r}
par(mfrow = c(1,2))
hist(Data,100)
hist(Data.remove,100)
```

```{r}
empirical.mean = c()
for( i in 1:500){
  Data.missing=replace(Data,sample(1000,i),NA)
  Data.remove=Data.missing[- which(is.na(Data.missing))]
  empirical.mean[i]=mean(Data.remove)
}
plot(empirical.mean, xlab="Number of missing values", ylab = "Mean of the new data set", main="Mean of the data set after removing the missing values", pch=20, lwd=2, col="blue")


```

### Method 2
```{r}
Data.missing=replace(Data, sample(1000, i), NA)
Data.replace=replace(Data.missing, which(is.na(Data.missing)), mean(Data.missing[- which(is.na(Data.missing))]))
sd(Data)
sd(Data.replace)
```

```{r}
empirical.sd=c()
for( i in 1:700){
  Data.missing=replace(Data,sample(1000,i),NA)
  Data.replace=replace(Data.missing,which(is.na(Data.missing)), mean(Data.missing[- which(is.na(Data.missing))]))
  empirical.sd[i]=sd(Data.replace)
}
plot(empirical.sd, xlab="Number of missing values", ylab = "sd of the new data set", main="sd of the data set after replacing the missing values by the mean", pch=20, lwd=2, col="blue")

```

